CREATE EXTENSION IF NOT EXISTS postgis SCHEMA extensions;

----------------------------domain-------------------------------------------------------------------------------------
CREATE DOMAIN public.sca_intensity AS SMALLINT
    CHECK (VALUE BETWEEN 0 AND 15);


CREATE TABLE public.products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_type TEXT NOT NULL
        CHECK (product_type IN ('coffee', 'machine')),

    name TEXT NOT NULL,
    brand TEXT,
    image_url TEXT,

    UNIQUE (id, product_type)
);


CREATE TABLE public.coffee_details (
    product_id INTEGER NOT NULL,

    product_type TEXT NOT NULL
        CHECK (product_type = 'coffee'),

    form TEXT NOT NULL
        CHECK (form IN ('ground', 'whole_bean', 'instant', 'capsule')),

    roast TEXT NOT NULL
        CHECK (roast IN ('light', 'medium', 'dark')),

    origin TEXT,

    process TEXT
        CHECK (process IN ('washed', 'natural', 'honey', 'anaerobic')),

    tasting_notes TEXT NOT NULL,

    aroma sca_intensity NOT NULL,
    flavor sca_intensity NOT NULL,
    aftertaste sca_intensity NOT NULL,
    acidity sca_intensity NOT NULL,
    sweetness sca_intensity NOT NULL,
    mouthfeel sca_intensity NOT NULL,

    floral sca_intensity NOT NULL,
    fruity sca_intensity NOT NULL,
    sour_fermented sca_intensity NOT NULL,
    green_vegetative sca_intensity NOT NULL,
    roasted sca_intensity NOT NULL,
    nutty_cocoa sca_intensity NOT NULL,
    spicy sca_intensity NOT NULL,
    sweet sca_intensity NOT NULL,

    PRIMARY KEY (product_id),

    FOREIGN KEY (product_id, product_type)
        REFERENCES public.products (id, product_type)
        ON DELETE CASCADE
);


CREATE TABLE public.machine_details (
    product_id INTEGER NOT NULL,

    product_type TEXT NOT NULL
        CHECK (product_type = 'machine'),

    machine_type TEXT NOT NULL
        CHECK (
            machine_type IN (
                'manual',
                'semi_automatic',
                'superautomatic',
                'capsule',
                'filter'
            )
        ),

    accepted_forms TEXT[] NOT NULL
        CHECK (
            cardinality(accepted_forms) > 0
            AND accepted_forms <@
                ARRAY[
                    'ground',
                    'whole_bean',
                    'capsule'
                ]::TEXT[]
        ),

    has_grinder BOOLEAN
        GENERATED ALWAYS AS (
            'whole_bean' = ANY(accepted_forms)
        ) STORED,

    has_milk_frother BOOLEAN NOT NULL,

    has_pid BOOLEAN NOT NULL,

    has_dual_boiler BOOLEAN NOT NULL,

    pump_pressure_bar NUMERIC
        CHECK (pump_pressure_bar > 0),

    PRIMARY KEY (product_id),

    FOREIGN KEY (product_id, product_type)
        REFERENCES public.products (id, product_type)
        ON DELETE CASCADE,

    CONSTRAINT machine_details_capsule_form_check
    CHECK (
        machine_type <> 'capsule'
        OR accepted_forms = ARRAY['capsule']::TEXT[]
    )
);


CREATE TABLE public.retailers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT NOT NULL UNIQUE,

    website_url TEXT NOT NULL,

    affiliate_id TEXT
);


CREATE TABLE public.prices (
    product_id INTEGER NOT NULL,

    retailer_id INTEGER NOT NULL,

    amount NUMERIC(12, 2) NOT NULL
        CHECK (amount > 0),

    currency TEXT NOT NULL
        CHECK (currency ~ '^[A-Z]{3}$'),

    url TEXT NOT NULL,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (product_id, retailer_id),

    FOREIGN KEY (product_id)
        REFERENCES public.products (id)
        ON DELETE CASCADE,

    FOREIGN KEY (retailer_id)
        REFERENCES public.retailers (id)
        ON DELETE CASCADE
);


CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


CREATE TRIGGER set_prices_updated_at
BEFORE UPDATE ON public.prices
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


ALTER TABLE public.products
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.coffee_details
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.machine_details
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.retailers
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.prices
    ENABLE ROW LEVEL SECURITY;

--------------------------------------AUTH & USERS---------------------------------------------------------------------------------------------------

CREATE TABLE public.profiles (
    id UUID NOT NULL
        REFERENCES auth.users
        ON DELETE CASCADE,

    role TEXT NOT NULL DEFAULT 'user'
        CHECK (role IN ('user', 'admin', 'shop_owner')),

    display_name TEXT,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);


ALTER TABLE public.profiles
    ENABLE ROW LEVEL SECURITY;


CREATE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.profiles (id)
    VALUES (NEW.id);

    RETURN NEW;
END;
$$;


CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE PROCEDURE public.handle_new_user();

    -----------------------------------------------SHOPS & SHOP HOURS------------------------------------------------------------------------

    CREATE EXTENSION IF NOT EXISTS postgis
    SCHEMA extensions;


CREATE TABLE public.shops (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT NOT NULL,

    address TEXT NOT NULL,

    phone TEXT,

    description TEXT,

    location extensions.geography(POINT, 4326) NOT NULL,

    services TEXT[] NOT NULL
        CHECK (
            cardinality(services) > 0
            AND services <@
                ARRAY[
                    'service',
                    'cafe',
                    'shop'
                ]::TEXT[]
        ),

    owner_id UUID
        REFERENCES public.profiles (id)
        ON DELETE SET NULL,

    is_demo BOOLEAN NOT NULL
        DEFAULT false,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);


CREATE INDEX shops_location_gist_idx
    ON public.shops
    USING GIST (location);


ALTER TABLE public.shops
    ENABLE ROW LEVEL SECURITY;


CREATE TABLE public.shop_hours (
    shop_id INTEGER NOT NULL,

    weekday SMALLINT NOT NULL
        CHECK (weekday BETWEEN 0 AND 6),

    opens TIME NOT NULL,

    closes TIME NOT NULL,

    CONSTRAINT shop_hours_opens_check
        CHECK (opens < closes),

    PRIMARY KEY (shop_id, weekday),

    FOREIGN KEY (shop_id)
        REFERENCES public.shops (id)
        ON DELETE CASCADE
);


COMMENT ON COLUMN public.shop_hours.weekday IS
    '0 = Sunday, 1 = Monday, ..., 6 = Saturday';


ALTER TABLE public.shop_hours
    ENABLE ROW LEVEL SECURITY;

--------------------------REVIEWS & COLLECTIONS --------------------------------------------------

CREATE TABLE public.reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    profile_id UUID
        REFERENCES public.profiles (id)
        ON DELETE SET NULL,

    product_id INTEGER NOT NULL
        REFERENCES public.products (id)
        ON DELETE CASCADE,

    rating SMALLINT NOT NULL,

    body TEXT,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT reviews_rating_check
        CHECK (rating BETWEEN 1 AND 5),

    CONSTRAINT reviews_profile_id_product_id_key
        UNIQUE (profile_id, product_id)
);


CREATE TRIGGER set_reviews_updated_at
BEFORE UPDATE ON public.reviews
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


ALTER TABLE public.reviews
    ENABLE ROW LEVEL SECURITY;


CREATE TABLE public.collections (
    profile_id UUID NOT NULL
        REFERENCES public.profiles (id)
        ON DELETE CASCADE,

    product_id INTEGER NOT NULL
        REFERENCES public.products (id)
        ON DELETE CASCADE,

    status TEXT NOT NULL,

    added_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT collections_status_check
        CHECK (status IN ('tried', 'want_to_try')),

    PRIMARY KEY (profile_id, product_id)
);


ALTER TABLE public.collections
    ENABLE ROW LEVEL SECURITY;

---------------------------------------------BOOKINGS-----------------------------------------------------------------------------------