CREATE DOMAIN public.sca_intensity AS SMALLINT
    CHECK (VALUE BETWEEN 0 AND 15);


CREATE TABLE public.products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_type TEXT NOT NULL
        CHECK (product_type IN ('coffee', 'machine')),

    name TEXT NOT NULL,
    brand TEXT,
    image_url TEXT,

    UNIQUE (id, product_type)
);


CREATE TABLE public.coffee_details (
    product_id INTEGER NOT NULL,

    product_type TEXT NOT NULL
        CHECK (product_type = 'coffee'),

    form TEXT NOT NULL
        CHECK (form IN ('ground', 'whole_bean', 'instant')),

    roast TEXT NOT NULL
        CHECK (roast IN ('light', 'medium', 'dark')),

    origin TEXT,

    process TEXT
        CHECK (process IN ('washed', 'natural', 'honey', 'anaerobic')),

    tasting_notes TEXT NOT NULL,

    aroma sca_intensity NOT NULL,
    flavor sca_intensity NOT NULL,
    aftertaste sca_intensity NOT NULL,
    acidity sca_intensity NOT NULL,
    sweetness sca_intensity NOT NULL,
    mouthfeel sca_intensity NOT NULL,

    floral sca_intensity NOT NULL,
    fruity sca_intensity NOT NULL,
    sour_fermented sca_intensity NOT NULL,
    green_vegetative sca_intensity NOT NULL,
    roasted sca_intensity NOT NULL,
    nutty_cocoa sca_intensity NOT NULL,
    spicy sca_intensity NOT NULL,
    sweet sca_intensity NOT NULL,

    PRIMARY KEY (product_id),

    FOREIGN KEY (product_id, product_type)
        REFERENCES public.products (id, product_type)
        ON DELETE CASCADE
);


ALTER TABLE public.products
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.coffee_details
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.machine_details (
    product_id INTEGER NOT NULL,

    product_type TEXT NOT NULL
        CHECK (product_type = 'machine'),

    machine_type TEXT NOT NULL
        CHECK (
            machine_type IN (
                'manual',
                'semi_automatic',
                'superautomatic',
                'capsule',
                'filter'
            )
        ),

    accepted_forms TEXT[] NOT NULL
        CHECK (
            cardinality(accepted_forms) > 0
            AND accepted_forms <@
                ARRAY[
                    'ground',
                    'whole_bean',
                    'capsule'
                ]::TEXT[]
        ),

    has_grinder BOOLEAN
        GENERATED ALWAYS AS (
            'whole_bean' = ANY(accepted_forms)
        ) STORED,

    has_milk_frother BOOLEAN NOT NULL,

    has_pid BOOLEAN NOT NULL,

    has_dual_boiler BOOLEAN NOT NULL,

    pump_pressure_bar NUMERIC
        CHECK (pump_pressure_bar > 0),

    PRIMARY KEY (product_id),

    FOREIGN KEY (product_id, product_type)
        REFERENCES public.products (id, product_type)
        ON DELETE CASCADE,

    CHECK (
        machine_type <> 'capsule'
        OR accepted_forms = ARRAY['capsule']::TEXT[]
    )
);

ALTER TABLE public.machine_details
    ENABLE ROW LEVEL SECURITY;