-- Coffee database schema.
-- Execution order:
-- 1. schema.sql
-- 2. seed.sql
-- 3. db/tests/constraints.sql
-- 4. db/tests/behaviour.sql
--
-- Supabase/PostgreSQL-specific objects:
-- auth.users, PostGIS (extensions), RLS.
--
-- Tables:
-- products, coffee_details, machine_details,
-- retailers, prices, profiles, shops, shop_hours,
-- reviews, collections, bookings.

DROP TRIGGER IF EXISTS on_auth_user_created
ON auth.users;

DROP TABLE IF EXISTS public.bookings CASCADE;
DROP TABLE IF EXISTS public.collections CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.shop_hours CASCADE;
DROP TABLE IF EXISTS public.shops CASCADE;
DROP TABLE IF EXISTS public.prices CASCADE;
DROP TABLE IF EXISTS public.retailers CASCADE;
DROP TABLE IF EXISTS public.machine_details CASCADE;
DROP TABLE IF EXISTS public.coffee_details CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

DROP FUNCTION IF EXISTS public.validate_booking_status_transition();
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP FUNCTION IF EXISTS public.set_updated_at();

DROP DOMAIN IF EXISTS public.sca_intensity;


CREATE EXTENSION IF NOT EXISTS postgis
    SCHEMA extensions;

CREATE EXTENSION IF NOT EXISTS btree_gist;


CREATE DOMAIN public.sca_intensity AS SMALLINT
    CONSTRAINT sca_intensity_check
    CHECK (VALUE BETWEEN 0 AND 15);


CREATE TABLE public.products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_type TEXT NOT NULL,

    name TEXT NOT NULL,

    brand TEXT,

    image_url TEXT,

    CONSTRAINT products_product_type_check
        CHECK (product_type IN ('coffee', 'machine')),

    UNIQUE (id, product_type)
);


CREATE TABLE public.coffee_details (
    product_id INTEGER NOT NULL,

    product_type TEXT NOT NULL,

    form TEXT NOT NULL,

    roast TEXT NOT NULL,

    origin TEXT,

    process TEXT,

    tasting_notes TEXT NOT NULL,

    aroma public.sca_intensity NOT NULL,
    flavor public.sca_intensity NOT NULL,
    aftertaste public.sca_intensity NOT NULL,
    acidity public.sca_intensity NOT NULL,
    sweetness public.sca_intensity NOT NULL,
    mouthfeel public.sca_intensity NOT NULL,

    floral public.sca_intensity NOT NULL,
    fruity public.sca_intensity NOT NULL,
    sour_fermented public.sca_intensity NOT NULL,
    green_vegetative public.sca_intensity NOT NULL,
    roasted public.sca_intensity NOT NULL,
    nutty_cocoa public.sca_intensity NOT NULL,
    spicy public.sca_intensity NOT NULL,
    sweet public.sca_intensity NOT NULL,

    PRIMARY KEY (product_id),

    CONSTRAINT coffee_details_product_type_check
        CHECK (product_type = 'coffee'),

    CONSTRAINT coffee_details_form_check
        CHECK (
            form IN (
                'ground',
                'whole_bean',
                'instant',
                'capsule'
            )
        ),

    CONSTRAINT coffee_details_roast_check
        CHECK (roast IN ('light', 'medium', 'dark')),

    FOREIGN KEY (product_id, product_type)
        REFERENCES public.products (id, product_type)
        ON DELETE CASCADE
);


CREATE TABLE public.machine_details (
    product_id INTEGER NOT NULL,

    product_type TEXT NOT NULL,

    machine_type TEXT NOT NULL,

    accepted_forms TEXT[] NOT NULL,

    has_grinder BOOLEAN
        GENERATED ALWAYS AS (
            'whole_bean' = ANY(accepted_forms)
        ) STORED,

    has_milk_frother BOOLEAN NOT NULL,

    has_pid BOOLEAN NOT NULL,

    has_dual_boiler BOOLEAN NOT NULL,

    pump_pressure_bar NUMERIC,

    PRIMARY KEY (product_id),

    CONSTRAINT machine_details_pump_pressure_bar_check
        CHECK (pump_pressure_bar > 0),

    CONSTRAINT machine_details_product_type_check
        CHECK (product_type = 'machine'),

    CONSTRAINT machine_details_machine_type_check
        CHECK (
            machine_type IN (
                'manual',
                'semi_automatic',
                'superautomatic',
                'capsule',
                'filter'
            )
        ),

    CONSTRAINT machine_details_accepted_forms_check
        CHECK (
            cardinality(accepted_forms) > 0
            AND accepted_forms <@
                ARRAY[
                    'ground',
                    'whole_bean',
                    'capsule'
                ]::TEXT[]
        ),

    CONSTRAINT machine_details_capsule_form_check
        CHECK (
            machine_type <> 'capsule'
            OR accepted_forms = ARRAY['capsule']::TEXT[]
        ),

    FOREIGN KEY (product_id, product_type)
        REFERENCES public.products (id, product_type)
        ON DELETE CASCADE
);


CREATE TABLE public.retailers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT NOT NULL,

    website_url TEXT NOT NULL,

    affiliate_id TEXT,

    CONSTRAINT retailers_name_unique
        UNIQUE (name)
);


CREATE TABLE public.prices (
    product_id INTEGER NOT NULL,

    retailer_id INTEGER NOT NULL,

    amount NUMERIC(12, 2) NOT NULL,

    currency TEXT NOT NULL,

    url TEXT NOT NULL,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (product_id, retailer_id),

    CONSTRAINT prices_amount_check
        CHECK (amount > 0),

    CONSTRAINT prices_currency_check
        CHECK (currency ~ '^[A-Z]{3}$'),

    FOREIGN KEY (product_id)
        REFERENCES public.products (id)
        ON DELETE CASCADE,

    FOREIGN KEY (retailer_id)
        REFERENCES public.retailers (id)
        ON DELETE CASCADE
);


CREATE TABLE public.profiles (
    id UUID NOT NULL
        REFERENCES auth.users
        ON DELETE CASCADE,

    role TEXT NOT NULL
        DEFAULT 'user',

    display_name TEXT,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),

    CONSTRAINT profiles_role_check
        CHECK (role IN ('user', 'admin', 'shop_owner'))
);


CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.profiles (id)
    VALUES (NEW.id);

    RETURN NEW;
END;
$$;


CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();


CREATE TABLE public.shops (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name TEXT NOT NULL,

    address TEXT NOT NULL,

    phone TEXT,

    description TEXT,

    location extensions.geography(POINT, 4326) NOT NULL,

    services TEXT[] NOT NULL,

    owner_id UUID,

    is_demo BOOLEAN NOT NULL
        DEFAULT false,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT shops_services_check
        CHECK (
            cardinality(services) > 0
            AND services <@
                ARRAY[
                    'service',
                    'cafe',
                    'shop'
                ]::TEXT[]
        ),

    FOREIGN KEY (owner_id)
        REFERENCES public.profiles (id)
        ON DELETE SET NULL
);


CREATE INDEX shops_location_gist_idx
    ON public.shops
    USING GIST (location);


CREATE TABLE public.shop_hours (
    shop_id INTEGER NOT NULL,

    weekday SMALLINT NOT NULL,

    opens TIME NOT NULL,

    closes TIME NOT NULL,

    PRIMARY KEY (shop_id, weekday),

    CONSTRAINT shop_hours_weekday_check
        CHECK (weekday BETWEEN 0 AND 6),

    CONSTRAINT shop_hours_opens_check
        CHECK (opens < closes),

    FOREIGN KEY (shop_id)
        REFERENCES public.shops (id)
        ON DELETE CASCADE
);


COMMENT ON COLUMN public.shop_hours.weekday IS
    '0 = Sunday, 1 = Monday, ..., 6 = Saturday';


CREATE TABLE public.reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    profile_id UUID,

    product_id INTEGER NOT NULL,

    rating SMALLINT NOT NULL,

    body TEXT,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT reviews_rating_check
        CHECK (rating BETWEEN 1 AND 5),

    CONSTRAINT reviews_profile_id_product_id_key
        UNIQUE (profile_id, product_id),

    FOREIGN KEY (profile_id)
        REFERENCES public.profiles (id)
        ON DELETE SET NULL,

    FOREIGN KEY (product_id)
        REFERENCES public.products (id)
        ON DELETE CASCADE
);


CREATE TABLE public.collections (
    profile_id UUID NOT NULL,

    product_id INTEGER NOT NULL,

    status TEXT NOT NULL,

    added_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (profile_id, product_id),

    CONSTRAINT collections_status_check
        CHECK (status IN ('tried', 'want_to_try')),

    FOREIGN KEY (profile_id)
        REFERENCES public.profiles (id)
        ON DELETE CASCADE,

    FOREIGN KEY (product_id)
        REFERENCES public.products (id)
        ON DELETE CASCADE
);


CREATE TABLE public.bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    profile_id UUID,

    shop_id INTEGER NOT NULL,

    service TEXT NOT NULL,

    starts_at TIMESTAMPTZ NOT NULL,

    ends_at TIMESTAMPTZ NOT NULL,

    status TEXT NOT NULL
        DEFAULT 'pending',

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT bookings_service_check
        CHECK (
            service IN (
                'consultation',
                'workshop',
                'repair'
            )
        ),

    CONSTRAINT bookings_status_check
        CHECK (
            status IN (
                'pending',
                'confirmed',
                'completed',
                'cancelled'
            )
        ),

    CONSTRAINT bookings_time_check
        CHECK (starts_at < ends_at),

    CONSTRAINT bookings_no_overlap
        EXCLUDE USING GIST (
            shop_id WITH =,
            tstzrange(starts_at, ends_at) WITH &&
        )
        WHERE (status <> 'cancelled'),

    FOREIGN KEY (profile_id)
        REFERENCES public.profiles (id)
        ON DELETE SET NULL,

    FOREIGN KEY (shop_id)
        REFERENCES public.shops (id)
        ON DELETE CASCADE
);


CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


CREATE TRIGGER set_prices_updated_at
    BEFORE UPDATE ON public.prices
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER set_reviews_updated_at
    BEFORE UPDATE ON public.reviews
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();


CREATE TRIGGER set_bookings_updated_at
    BEFORE UPDATE ON public.bookings
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();


CREATE OR REPLACE FUNCTION public.validate_booking_status_transition()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'pending' THEN
            RAISE EXCEPTION 'Invalid initial booking status: %', NEW.status
                USING ERRCODE = 'check_violation';
        END IF;

        RETURN NEW;
    END IF;

    IF OLD.status = 'pending'
       AND NEW.status NOT IN ('pending', 'confirmed', 'cancelled') THEN
        RAISE EXCEPTION
            'Invalid booking status transition: pending -> %',
            NEW.status
            USING ERRCODE = 'check_violation';
    END IF;

    IF OLD.status = 'confirmed'
       AND NEW.status NOT IN ('confirmed', 'completed', 'cancelled') THEN
        RAISE EXCEPTION
            'Invalid booking status transition: confirmed -> %',
            NEW.status
            USING ERRCODE = 'check_violation';
    END IF;

    IF OLD.status IN ('completed', 'cancelled')
       AND NEW.status <> OLD.status THEN
        RAISE EXCEPTION
            'Invalid booking status transition: % -> %',
            OLD.status,
            NEW.status
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$;


CREATE TRIGGER validate_booking_status_insert
    BEFORE INSERT ON public.bookings
    FOR EACH ROW
    EXECUTE FUNCTION public.validate_booking_status_transition();


CREATE TRIGGER validate_booking_status_update
    BEFORE UPDATE OF status ON public.bookings
    FOR EACH ROW
    WHEN (OLD.status IS DISTINCT FROM NEW.status)
    EXECUTE FUNCTION public.validate_booking_status_transition();


ALTER TABLE public.products
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.coffee_details
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.machine_details
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.retailers
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.prices
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.profiles
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.shops
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.shop_hours
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.reviews
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.collections
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.bookings
    ENABLE ROW LEVEL SECURITY;